AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - bin/**
    - spec/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
